//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public CreditCard()
        {
            this.Accounts = new HashSet<Account>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int CreditCardId { get; set; }
        public long CreditCardNumber { get; set; }
        public byte CardType { get; set; }
        public int Limit { get; set; }
        public decimal Balance { get; set; }
        public byte ExpirationMonth { get; set; }
        public byte ExpirationYear { get; set; }
        public Nullable<int> CreditCardUser_PersonId { get; set; }
        public Nullable<int> Account_AccountId { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual Account Account { get; set; }
        public virtual Person CreditCardUser { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
