//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Accounts = new HashSet<Account>();
            this.CreditCards = new HashSet<CreditCard>();
        }
    
        public int PersonId { get; set; }
        public byte Age { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public byte Permissions { get; set; }
        public Nullable<int> Address_AddressId { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual Address Address { get; set; }
        public virtual ICollection<CreditCard> CreditCards { get; set; }
    }
}
