//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public decimal Amount { get; set; }
        public byte TransactionDay { get; set; }
        public byte TransactionMonth { get; set; }
        public byte TransactionYear { get; set; }
        public string BusinessName { get; set; }
        public Nullable<int> CreditCard_CreditCardId { get; set; }
    
        public virtual CreditCard CreditCard { get; set; }
    }
}
